language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
#  - "nightly" # currently points to 3.7-dev

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install codecov"

# command to run tests
# Use --nocapture with nosetests to get extra verbose output for debugging on Travis
script:
  - nosetests -v --with-coverage --cover-package=diagnostic_primers

# application dependencies: BLAST+, legacy BLAST, Primer3, EMBOSS, Prodigal
before_install:
  - cd $HOME
  # Install BLAST
  - wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/2.2.26/blast-2.2.26-x64-linux.tar.gz
  - tar -zxf blast-2.2.26-x64-linux.tar.gz
  - export PATH=$HOME/blast-2.2.26/bin:$PATH
  - mkdir primer3
  - cd primer3
  - wget https://sourceforge.net/projects/primer3/files/primer3/1.1.4/primer3-1.1.4.tar.gz
  - tar -zxf primer3-1.1.4.tar.gz
  - cd src
  - make all
  - export PATH=$HOME/primer3/src:$PATH  
  - cd $HOME
  - mkdir prodigal
  - cd prodigal
  - wget https://github.com/hyattpd/Prodigal/releases/download/v2.6.3/prodigal.linux
  - cp prodigal.linux prodigal
  - chmod 755 prodigal
  - export PATH=$HOME/prodigal:$PATH
  - cd $HOME
  - cd $TRAVIS_BUILD_DIR

dist: trusty
sudo: false
addons:
  apt:
    packages:
    - ncbi-blast+
    - emboss

# Use codecov for code coverage
after_success:
  - codecov

# Send Travis-CI updates to Slack
notifications:
  slack:
    secure: l0CfKvamI2SZFvgSsVMQhad6nbXGS42TKKvX4Iv9zL+T1nAIh47hOtko0f/GwtxUU3d+7O30iGM33yqDN9o9tIb2FkxG7atnKxpzLev2/Z0LuyBHQvD54o91ihJRowV5O0PALMzbOdN3qQIoUBFq9ohF9Dd+X/OymImYSdtTMzI0o2QmDnDxHtyKAc3bqS1OmnGraiEy4A7HnwL70mUDfhJapuyLuCDCI4mTGCtbjSCwlyObvCpUt0BwTtcEH5sysn0nlmeqMMpN74Z32coRJTXMtwb2Qgk8aof+IcDJ3HKpM0LHg5l/BiqCfCmEUXpFO/UKg48TY3kSUWlTRg75Ch+BzHHahIhlYg0JaQHWb9HtxXzWfQUh7pTivB0H5D2dhF1l7O+W5/D17iAzJbKnHbr3v3k1kQ9pi7sPxZOlauUSEvgSGcytVVmU9AbZAMo7lMys5mPozF6kdddA1+Ul85Pc/sKbTDOGnbSnswknO++WGV4Po3r36w2ZJCM3mtADKpB1YlyP0pGV66lykD3snSyudNQVbJL9x9W1p0rwLZA+cZyZlYEprtDPfexkCGSeFtOJkJOilt6OPe/GxG39TX8D4dit61/6JVJVru5FwbGj6piFxOZmzzz6sgyIGZsMCQKfd1dIR16qosAFnayxEC391IJ7Y3rlfr89ESBcYwE=
    